<!DOCTYPE HTML>
<head>
	<meta http-equiv="content-type" content="text/html" />
	<meta charset="utf-8">
		<title>Tratamiento de Control de Obligacion</title>
		<link href="<?php echo Conectar::ruta();?>public/css/bootstrap.css" rel="stylesheet">
		<script ></script>
<!--  centrar tablas style="margin: 0 auto;" --> 
</head>

<body>
<div class="container">
		    <div class="well">
    			<h2 align="center">Relacion de Control de Pagos</h2>
    		</div>

			  <a href="<?php echo Conectar::ruta()?>?accion=obligacion" > Nuevo Documento Pago</a>
			  <br />
			  <p align="center"><a href="<?php echo Conectar::ruta() ?>?accion=home">Volver</a></p>
			  <hr />
			  <br /><br />
				<table class="table table-striped table-bordered table-condensed" >
					<tr style="background-color: #E0ECFF;"	>
						<td>Contrato</td>
						<td>Obligacion</td>
						<td>Proveedor</td>
						<td>Concepto</td>
						<td>Fecha</td>
						<td>Opago</td>
						<td>Egreso</td>
						<td >Detalle</td>
					</tr>
					<?php 
					//print_r($deto);
					 foreach($deto as $d)
					 { 
					?>
					<tr >
						<td valign="top" width="50"><?php echo $d["num_contrato"];?></td>
						<td valign="top" align="center"width="50"><?php echo $d["id_obligacion"];?></td>
						<td valign="top" width="200"><?php echo $d["nombre"];?></td>
						<td valign="top" align="justify" width="400"><?php echo $d["detalle"];?></td>
						<td valign="top" width="50"><?php echo $d["fechaobliga"];?></td>
						<td valign="top" align="center" width="50"><?php echo $d["id_opago"];?></td>
						<td valign="top" align="center" width="50"><?php echo $d["id_egreso"];?></td>
					    <td valign="top" width="50"><a href="<?php echo Conectar::ruta()?>?accion=oblideta&id=<?php echo $d["id_obligacion"];?>">Ver/Agregar</a></td>
					</tr>
					<?php 
					 }
					?>
				</table>
				<div class="pagination">
					<?php $paginacion->render(); ?>	  
				</div>
</div>
<?php require_once("public/layout/footer.php") ?>
</body>
</html>