<!DOCTYPE html>

<html>

    <head>
        <title>Crar Egreso</title>
        <meta charset="utf-8">
        <link rel="stylesheet" href="<?php echo Conectar::ruta();?>/public/css/zebra_form.css">
        <script src="<?php echo Conectar::ruta();?>/public/js/jquery-1.8.3.js"></script>
        <script src="<?php echo Conectar::ruta();?>/public/js/zebra_form.js"></script>
        <script >
		function volver()
		{
			window.location="<?php echo Conectar::ruta();?>?accion=paraegreso"
		}
	</script>
        <style type="text/css">
        	#formulario
        	{
				margin:50px auto;
				width: 500px;
				padding: 10px 20px 10px 20px;
				border-radius:20px;
				border: 2px dashed #CCC;
				box-shadow: 0px 0px 5px #000;
				background: white;
				
				}
        </style>
 </head>

    <body>
		<div id="formulario">
			<?php
				if(isset($_GET["m"]))
				{
					switch($_GET["m"])
					{
						       case '2' :
								   ?>
								        <h2 style="color: green">Datos Grabados Satisfactoriemente</h2>
								   <?php
					}
				}
				
				$egres=$neg["can"];
				$egres++;
						
				// include the Zebra_Form class
				require '/public/Zebra_Form.php';
				
				// instantiate a Zebra_Form object
				$form = new Zebra_Form('form','post','');
				// numero de Egreso
				$form->add('label', 'label_negreso', 'negreso', 'Numero Egreso');
				$obj = &$form->add('text', 'negreso',$egres);
				$obj->set_rule(array( 
				'required' => array('error', 'Digite Numero Egreso!'), 
				 'number'    =>  array('', 'error', 'Solo Numeros!'),
				));
				//proveedor/*
		        $form->add('label', 'label_prov', 'id_prov', 'Seleccione Proveedor');;
				$obj = &$form->add('select', 'id_prov');
				foreach($pro as $p)
				{
					 
					$data=array($p["id_proveedor"]=>substr($p["nombre"],0,45));
					$obj->add_options($data); 
				}
				$obj->set_rule(array( 'required' => array('error', 'Seleccione el Proveedor!') ));
				
				//fecha Egreso
				$form->add('label', 'label_fec', 'fecha', 'Fecha Egreso');
				$obj = &$form->add('date', 'fecha',date('Y-m-d'));
				$obj->set_rule(array('date' => array( 'error','Invalid date!' )));
				//Detalle Egreso
				$form->add('label', 'label_objc', 'detaegr', 'Detalle Egreso');
				$obj = &$form->add('textarea', 'detaegr');
				$obj->set_rule(array( 'required' => array('error', 'Escriba Detalle del Egreso!')));
				 //Banco
				$form->add('label', 'label_tcon', 'numban', 'Seleccione Banco');
				$obj = &$form->add('select', 'numban');
				foreach($ban as $b)
				{  
					$data=array($b["id_banco"]=>$b["nombreban"]." ".$b["cuenta"]);
					$obj->add_options($data); 
				}
				$obj->set_rule(array( 'required' => array('error', 'Seleccione el Banco!') ));
				// Valor egreso
				$form->add('label', 'label_vcon', 'vegre', 'Valor Egreso');
				$obj = &$form->add('text', 'vegre');
				$obj->set_rule(array( 
				'required' => array('error', 'Digite Valor del Egreso!')));
				//fecha junta
				$form->add('label', 'label_fej', 'fechaj', 'Fecha Junta');
				$obj = &$form->add('date', 'fechaj',date('Y-m-d'));
				$obj->set_rule(array('date' => array( 'error','Invalid date!' )));
				//fecha factura
				$form->add('label', 'label_fef', 'fechaf', 'Fecha Factura');
				$obj = &$form->add('date', 'fechaf',date('Y-m-d'));
				$obj->set_rule(array('date' => array( 'error','Invalid date!' )));
				//fecha recibido
				$form->add('label', 'label_fer', 'fechar', 'Fecha Recibido');
				$obj = &$form->add('date', 'fechar',date('Y-m-d'));
				$obj->set_rule(array('date' => array( 'error','Invalid date!' )));
				
				$form->add('label', 'label_numche', 'ncheque', 'Numero Cheque');
				$obj = &$form->add('text', 'ncheque');
				
				$form->add('label', 'label_nomche', 'nomcheque', 'Cheque a Nombre');
				$obj = &$form->add('text', 'nomcheque');
				
				$form->add('label', 'label_feche', 'fecheq', 'Fecha Cheque');
				$obj = &$form->add('date', 'fecheq',date('Y-m-d'));
				$obj->set_rule(array('date' => array( 'error','Invalid date!' )));
				
				
				$obj = &$form->add('hidden', 'grabar','si');
								
				// enviar formulario
				$form->add('submit', 'btnsubmit', 'Guardar');
				
				// validate the form
				if ($form->validate()) {
				
				    // do stuff here
				 $date = $obj->get_date();
				}
				
				// auto generate output, labels above form elements
				$form->render();
				
				 	?>
				 <center>
			    	 <input  type="button" value="Volver" onclick="volver()">
			     </center>
				<?php
		  ?>
	</div>
    </body>

</html>

