<!DOCTYPE html>

<html>

    <head>
        <title>Crar Planillas</title>
        <meta charset="utf-8">
        <link rel="stylesheet" href="<?php echo Conectar::ruta();?>/public/css/zebra_form.css">
        <script src="<?php echo Conectar::ruta();?>/public/js/jquery-1.8.3.js"></script>
        <script src="<?php echo Conectar::ruta();?>/public/js/zebra_form.js"></script>
        <script src="<?php echo Conectar::ruta();?>public/js/funcionesjquery.js"></script>
        <script >
		function volver()
		{
			window.location="<?php echo Conectar::ruta();?>?accion=home"
		}
	</script>
        <style type="text/css">
        	#formulario
        	{
				margin:100px auto;
				width: 500px;
				padding: 10px 20px 10px 20px;
				border-radius:20px;
				border: 2px dashed #CCC;
				box-shadow: 0px 0px 5px #000;
				background: white;
				
				}
        </style>
 </head>

    <body onload="mueveReloj('contenedor_reloj')" bgcolor="#D8D8D8" >
    	<h1 align="center" > Crear Planilla </h1>
    	  <strong style="color: #0489B1;">Usuario (a):</strong> @_<?php echo $_SESSION["ses_nombre"];?>
          <div id="contenedor_reloj" style="color:#FFFFFF; background-color:#58ACFA "></div>
    	<hr style="color: #FFFFFF" />
		<div id="formulario">
			<?php
			if(isset($_GET["m"]))
			{
				switch($_GET["m"])
					{
						       case '1' :
								   ?>
								        <h2 style="color: green">Datos Grabados Satisfactoriemente</h2>
								   <?php
					}
			}
			$np=$capl["can"];
			$np++;
			 // include the Zebra_Form class
				require '/public/Zebra_Form.php';
				
				// instantiate a Zebra_Form object
				$form = new Zebra_Form('form','post','');
				
				// numero de planilla
				$form->add('label', 'label_pla', 'nump', 'Numero Planilla');
				$obj = &$form->add('text', 'nump',$np);
				$obj->set_rule(array( 
				'required' => array('error', 'Digite Numero Contrato!'), 
				 'number'    =>  array('', 'error', 'Solo Numeros!'),
				));
				//fecha/*
				$form->add('label', 'label_fe', 'fep', 'Fecha Planilla');
				$obj = &$form->add('date', 'fep',date('Y-m-d'));
				$obj->set_rule(array('date' => array( 'error','Invalid date!' )));
		       					
				$obj = &$form->add('hidden', 'grabar','si');
				// enviar formulario
				$form->add('submit', 'btnsubmit', 'Guardar');
				
				// validate the form
				if ($form->validate()) {
				
				    // do stuff here
				 $date = $obj->get_date();
				}
				
				// auto generate output, labels above form elements
				$form->render();
				
				 	?>
				 <center>
			    	 <input  type="button" value="Volver" onclick="volver()">
			     </center>
				<?php
		  ?>
	</div>
    </body>

</html>

