<?php
Conectar::plantilla_menu();
?>
		<div class="container">
			<div class="well">
    			<h2 align="center">Ordenes de Pago</h2>
    		</div>
    		<!--<div class="well">
    			<h2 align="center">OJO! TODAVIA NO USAR ESTA APLICACION</h2>
    		</div>-->
			<form name="form" action="" method="post" class="form-horizontal">
		
			<div class="control-group">
	            	<label class="control-label" for="select01">Numero Opago</label>
	           		 <div class="controls">
	           				<input  class="input" type="text"   name="numo" value="<?php echo $opr2["numorden"];?>" placeholder="Colocar Num Opago…" required/> 
	           		</div>
	          </div>
	         <div class="control-group">
	            	<label class="control-label" for="select01">Proveedor</label>
	           		 <div class="controls">
	           				<input  class="input" type="text"   name="prove" value="<?php echo $opr2["nombre"];?>" readonly/> 
	           		</div>
	          </div>
	         
	         <div class="control-group">
	            	<label class="control-label" for="select01">Fecha Opago</label>
	           		 <div class="controls">
	           				<input  class="input-small" type="text" id="datepicker"  name="fe" value="<?php echo $opr2["fecha"];?>" placeholder="Colocar Fecha…" required/> 
	           		</div>
	          </div>
	          <div class="control-group">
	            	<label class="control-label" for="select01">Sub Total</label>
	           		 <div class="controls">
	           				<input  class="input" type="number"   name="valorsiva"  value="<?php echo $opr2["totsiniva"];?>" placeholder="Colocar Valor antes de iva" required/> 
	           		</div>
	          </div>
	          <div class="control-group">
	            	<label class="control-label" for="select01">Iva</label>
	           		 <div class="controls">
	           				<input  class="input" type="number"   name="valoriva" value="<?php echo $opr2["valor_iva"];?>"   placeholder="Colocar Valor de iva" required/> 
	           		</div>
	          </div>
	          <div class="control-group">
	            	<label class="control-label" for="select01">Total Sin Los Descuentos</label>
	           		 <div class="controls">
	           				<input  class="input" type="number"   name="valorsdes"  value="<?php echo  $opr2["total"];?>"  readonly/> 
	           		</div>
	          </div>
	          <div class="control-group">
					<label class="control-label" for="textarea">Detalle</label>
					<div class="controls">
						<textarea  class="input-xlarge" name="deta" rows="3" cols="40"><?php echo $opr2["detalle"];?></textarea>
					</div>
			</div>
  
    <table width="400">
			<tr style="background-color: #C0C0C0">
				<td>Retencion	</td>
				<td>Porcentaje</td>
				<td>Base</td>
				<td>total</td>
			</tr>
			<tr >
						<td>	
							<select name="rete" id="rete1">
						  	<option value="0">Seleccion</option>
						  	<?php
						  	$s=0;
						  	   foreach($re1 as $d)
							   {
							?>   	
							    	<option value="<?php echo $d["id_reten"] ?>"><?php echo $d["Nombre_rete"] ?></option>
							<?php	
							   }
						  	?>
						  </select>	
						</td>
						<td>
							<input id="retenc1" type="text" name="ret" size="4" readonly/>
						</td>
						<td><input  type="text" name="base"  size="10"  onblur="calcular();"/></td>
						<td><input  type="text" name="total"  size="10"/></td>
						 <td><a  href="javascript:void(0);"  title="agregar detalle o Ver detalles" onclick="from_post('<?php echo $opr2["id_opago"]?>',
							document.form.base.value,document.form.rete.value,document.form.total.value,document.form.ret.value,'reporte','controller/opagosdetagraController.php')" > Add</a> </td>
			</tr>
	</table>
		<div  id="reporte">
				<table width="500" >
			      <?php
			       
			         //print_r($deta);
			         $s=0;
			         foreach($deta1 as $d)
					 {
					 	 if ($d["id_retencion"]!=17)
						   {$s=$s+$d["totalreten"];} 
			       ?>
					<tr>
						<td align="left" width="180"><?php echo $d["Nombre_rete"];?></td>
						<td  align="center" width="45"><?php echo $d["porcentaje"]; ?></td>
						<td align="right" width="80"><?php echo $d["base"]; ?></td>
						<td align="right" width="80"><?php echo $d["totalreten"]; ?></td>
						<td width="25" ><a href="javascript:void(0)" title="Eliminar Detalle" onclick="eliminar('<?php echo $d["id_opago"] ;?>','<?php echo $d["id_deta"] ;?>',
							'<?php echo $d["totalreten"]; ?>','<?php echo $d["id_retencion"]; ?>','reporte','controller/elim_deta_opaController.php')">Eliminar</a></td>
						
					</tr>
					
					<?php
					 }
					?>
					<tr>
						<td style="color: red;" align="right" colspan="3">Neto Pagar:</td>
						<td align="right" ><?php echo number_format($netpa1["sindes"]-$s,2); ?></td>
					</tr>
					
				</table>

		</div>
			 <input type="hidden"  name="editar"  value="si"/>
			 <input type="hidden"  name="id_op"  value="<?php echo $opr2["id_opago"];?>"/>
			 
			 <div class="form-actions">
	            <button type="submit" title="Grabar y Salir" class="btn btn-primary">Grabar</button>
	            <input class="btn" type="button" title="Cancelar Operación" value=" Cancelar " onclick="volver('<?php Conectar::ruta() ;?>?accion=editar_opago')"/>
          	  </div>
		</form>
		
		
 <?php
 require_once("public/layout/footer.php")
?>