<?php
Conectar::plantilla_menu();
?>
		<div class="container">
			<div class="well">
    			<h2 align="center">Eliminar Egresos</h2>
    		</div>
				 <div class="modal  hide fade " id="myModal" >
				    <div class="modal-header">
					    <button  type="button"class="close" title="Cerrar" data-dismiss="modal" aria-hidden="true">×</button>
					    <h3>Eliminar Egresos</h3>
				    </div>
				    <div class="modal-body">
				    		    <form class="well" method="post" name="form">
								    <label>Número Egreso</label>
								    <input type="text" name="numegre" class="span3" placeholder="Escribe Numero…">
								    <span class="help-inline">Solo Números!</span><br />
								    <button type="button" title="Buscar"  class="btn btn-primary" onclick="bucaregreso(document.form.numegre.value)">Buscar</button>
								    <label>O. pago</label>
								    <div class="controls">
								    	<input type="text" name="num_opago" class="span3" placeholder="Opago Numero…" readonly>
								    </div>
								    <input type="hidden" name="id_opago" >
								    <input type="hidden" name="id_egre" >
								</form>
								<div id="vista"></div>
				     </div>
				    <div class="modal-footer">
				    	<button type="button" title="Buscar"  class="btn btn-primary" onclick="eliminar_egreso(document.form.id_egre.value,document.form.id_opago.value)">Eliminar</button>
				    	<a href="#" class="btn" title="Cerrar" data-dismiss="modal" >Cerrar</a>
				     </div>
		    </div>	
			<a data-toggle="modal" href="#myModal" class="btn btn-primary btn-large">Eliminar Egreso</a>
		</div>
		
 <?php
 require_once("public/layout/footer.php")
?>