<!DOCTYPE html>
<html lang="es">
<head>
	<meta charset="utf-8">
	<title>Ingreso al Sistema</title>
	<link rel="stylesheet" media="screen" href="<?php echo Conectar::ruta();?>public/css/styles.css" >
    
</head>
<body>
 Su Cuenta de Licencia Freeware Expiro!!!!<br>
 Envienos un correo con su información y se le renovara un año mas de licencia gratis<br>
 
 Gracias Por Preferirnos!!! Web Hosting 
</body>
</html>