<?php
Conectar::plantilla_menu();
?>

<div class="container">
	<div class="well">
    			<h2 align="center">Libro de Banco</h2>
    </div>
  <form action="" method="post" name="form">  
   <center>
	    Entre
	    <input  class="fechajquery"   type="text"  name="feini" placeholder="Fecha Inicial…" required/> y
			        
		<input  class="fechajquery"   type="text"  name="fefin" placeholder="Fecha Final…" required/> 
		<label>Debitado del Banco</label>
		<div class="controls">
			<select name="banc" onchange="buscar_saldo(document.form.banc.value)">
				<option value="0">Seleccionar</option>
				<?php foreach($lba as $l) 
				{
				?>
					<option value="<?php echo $l["id_banco"];?>"><?php echo $l["nombreban"]." ".$l["cuenta"]; ?></option>
				<?php 
				}
				?>
			</select>
		</div>
		<div class="controls">
			Saldo que Viene: <input type="text" name="valor" id="saldo" readonly/>
		</div>
		<input class="btn btn-primary" type="button" " value=" Procesar " title="Procesar" onclick="repor_libro_ban(document.form.feini.value,document.form.fefin.value,document.form.banc.value)" />
	 </center>    
   </form> 
    <a href="javascript:void(0);" title="Pasar a Pdf" onclick="volver('<?php Conectar::ruta() ;?>?accion=libro_banco_pdf&fe1='+document.form.feini.value+'&fe2='+document.form.fefin.value+'&id='+document.form.banc.value)">Pdf</a>
    <div id="reporte_lib"></div>
</div>

<?php
 require_once("public/layout/footer.php")
?>
