<?php
Conectar::plantilla_menu();
?>

<div class="container">
	<div class="well">
    			<h2 align="center">Ordenes de Pago Por Egreso</h2>
    </div>
		<?php// print_r($datop);?>
			<a href="<?php echo Conectar::ruta();?>?accion=home">Atras</a>
				
				<table class="table table-striped table-bordered table-condensed">
					<tr >
						<th>Opago</th>
						<th>Contrato</th>
						<th>Proveedor</th>
						<th>Fecha</th>
						<th>Valor</th>
						<th>Neto Pagar</th>
						<th>Pagar</th>
					</tr>
					<?php 
					foreach($datop as $d)
					{
					?>
					<tr>
						<td align="center"><?php echo $d["numorden"];?></td>
						<td align="center"><?php echo $d["num_contrato"];?></td>
						<td align="center"><?php echo $d["nombre"];?></td>
						<td align="center"><?php echo $d["fecha"];?></td>
						<td align="right"><?php echo number_format($d["total"],2);?></td>
						<td align="right"><?php echo $d["neto_pagar"];?></td>
						<td align="right"><a href="<?php echo Conectar::ruta();?>?accion=crearegreso&nop=<?php echo $d["numorden"];?>
						">Pagar</a></td>
					</tr>
				    <?php
					  }
				    ?>
				</table>
				<div class="pagination">
					<?php $paginacion->render(); ?>	  
				</div>
</div>
				
	</div>




<?php
 require_once("public/layout/footer.php")
?>




