<?php
require_once("public/fpdf/fpdf.php");
class PDF extends FPDF
{
		private $valo;
		
		//Cabecera de página
	function vervalo($fe)
	{
		$this->valo=$fe;
	}
	//Cabecera de página
	
	function Header()
	{
	    { $this->Image('public/img/header_orden_pago.jpg',10,10,195,25);
			 $this->SetFont('Arial','B',9);$this->Ln(20);
			 $ver='INFORME RECAUDO DE FONDOS';
			 $w=$this->GetStringWidth($ver);
			 $this->SetX((216-$w)/2);
		     $this->Cell($w,5,$ver); $this->Ln();
			 $this->SetFont('');
			 $ver2='CUADRO DE INGRESOS';
			 $w=$this->GetStringWidth($ver2);
			 $this->SetX((216-$w)/2);
		     $this->Cell($w,5,$ver2);$this->Ln();
			 $ver3='FECHA : '.$this->valo;
			 $w=$this->GetStringWidth($ver3);
			 $this->SetX((216-$w)/2);
		     $this->Cell($w,5,$ver3);  
			 $this->Ln();$this->Ln();
			 $this->SetLineWidth(0.5);
			 $this->Cell(10,5,"ITEM",1,0,'C'); 
			 $this->Cell(20,5,"RECAJA No.",1,0,'C');
			 $this->Cell(25,5,"VALOR RC",1,0,'C');
			 $this->Cell(20,5,"EFECTIVO",1,0,'C');
			 $this->Cell(25,5,"BB 302-964150",1,0,'C');
			 $this->Cell(25,5,"BB 090-453895",1,0,'C');
			 $this->Cell(25,5,"BB 302-96444-0",1,0,'C');
			 $this->Cell(25,5,"CM 805-0201110",1,0,'C');
			 $this->Cell(25,5,"BO 387-048028",1,0,'C');	$this->Ln(); 
			 
		}
	   		
	    }

	//Pie de página
	function Footer()
	{
	    //Posición: a 1,5 cm del final
	    //$this->SetXY(-15);
	    
	 			$this->SetXY(10,-15);
			    //Arial italic 8
			    $this->SetFont('Arial','I',8);
			    //Número de página
			    $this->Cell(35,5,'CODIGO: F09-PGF-S02');
				$ver='VERSION: 01';
				$w=$this->GetStringWidth($ver);
				$this->SetX((216-$w)/2);
			    $this->Cell($w,5,$ver); 
				$ver2='FECHA DE VIGENCIA: 01/04/2009';
				$w=$this->GetStringWidth($ver2)+10;
				$this->SetX((216-$w));
				$this->Cell($w,5,$ver2); 
		
	}
}

$pdf=new PDF('P', 'mm', 'Letter');
	$pdf->AliasNbPages();
	$pdf->vervalo($_GET["fe1"]);
	$pdf->AddPage();
	$ite=1;
	$s=0;
	$pdf->SetLineWidth(0.3);
	foreach($rep as $l)
	{
		$pdf->Cell(10,5,$ite++,'LR',0,'C'); 
		$pdf->Cell(20,5,$l["numrecaja"],'LR',0,'C');
		$pdf->Cell(25,5,number_format($l["valorec"],2),'LR',0,'R');
		$pdf->Cell(20,5,number_format($l["valorec"],2),'LR',0,'R');
		if($l["id_banco"]==1){$pdf->Cell(25,5,number_format($l["valorec"],2),'LR',0,'R');}else{$pdf->Cell(25,5,"",'LR',0,'R');}
		if($l["id_banco"]==2){$pdf->Cell(25,5,number_format($l["valorec"],2),'LR',0,'R');}else{$pdf->Cell(25,5,"",'LR',0,'R');}
		if($l["id_banco"]==3){$pdf->Cell(25,5,number_format($l["valorec"],2),'LR',0,'R');}else{$pdf->Cell(25,5,"",'LR',0,'R');}
		if($l["id_banco"]==4){$pdf->Cell(25,5,number_format($l["valorec"],2),'LR',0,'R');}else{$pdf->Cell(25,5,"",'LR',0,'R');}
		if($l["id_banco"]==5){$pdf->Cell(25,5,number_format($l["valorec"],2),'LR',0,'R');}else{$pdf->Cell(25,5,"",'LR',0,'R');}
		$s +=$l["valorec"];
		$pdf->Ln();
	}
	$pdf->Cell(10,5,"",'LR',0,'C'); 
	$pdf->Cell(20,5,"",'LR',0,'C');
	$pdf->Cell(25,5,"",'LR',0,'L');
	$pdf->Cell(20,5,"",'LR',0,'C');
	$pdf->Cell(25,5,"",'LR',0,'C');
	$pdf->Cell(25,5,"",'LR',0,'C');
	$pdf->Cell(25,5,"",'LR',0,'C');
	$pdf->Cell(25,5,"",'LR',0,'C');
	$pdf->Cell(25,5,"",'LBTR',0,'C');$pdf->Ln();
	for ($i=0; $i < 3; $i++) { 
		$pdf->Cell(10,5,"",'LR',0,'C'); 
		$pdf->Cell(20,5,"",'LR',0,'C');
		$pdf->Cell(25,5,"",'LR',0,'L');
		$pdf->Cell(20,5,"",'LR',0,'C');
		$pdf->Cell(25,5,"",'LR',0,'C');
		$pdf->Cell(25,5,"",'LR',0,'C');
		$pdf->Cell(25,5,"",'LR',0,'C');
		$pdf->Cell(25,5,"",'LR',0,'C');
		$pdf->Ln(); 
	}
	$pdf->SetFont('Arial','',9);
	$pdf->Cell(30,5,"SUMAS",1,0,'C'); 
	$pdf->Cell(25,5,number_format($s,2),1,0,'R');
	$pdf->Cell(20,5,"",1,0,'C');
	$pdf->Cell(25,5,"",1,0,'C');
	$pdf->Cell(25,5,"",1,0,'C');
	$pdf->Cell(25,5,"",1,0,'C');
	$pdf->Cell(25,5,"",1,0,'C');
	$pdf->Ln();	
	$pdf->Cell(30,5,"SALDO ANTERIOR",1,0,'L'); 
	$pdf->Cell(25,5,"",1,0,'R'); $pdf->Ln();
	$pdf->Cell(30,5,"TOTAL RECI CAJA",1,0,'L'); 
	$pdf->Cell(25,5,number_format($s,2),1,0,'R');$pdf->Ln();
	$pdf->Cell(30,5,"TOTAL CONSGNES",1,0,'L'); 
	$pdf->Cell(25,5,number_format($s,2),1,0,'R');$pdf->Ln();
	$pdf->Cell(30,5,"SALDO CAJA",1,0,'L'); 
	$pdf->Cell(25,5,"",1,0,'R');$pdf->Ln();
	$pdf->SetLineWidth(0.5);
	$pdf->SetFont('Arial','B',9);
	$pdf->Cell(30,5,"TOTAL MOV. DIA",1,0,'L'); 
	$pdf->Cell(25,5,number_format($s,2),1,0,'R');
	$pdf->Cell(20,5,"",0,0,'C');
	$pdf->Cell(50,5,"FIRMA CAJERO",'T',0,'C');$pdf->Ln(); 
	$pdf->SetFont("");
	$pdf->SetLineWidth(0.3);
	$tc=0;
	for ($i=0; $i < 5 ; $i++) { //por los 5 Bancos
		$s=0;
	    $cue="";
		foreach($rep as $l) //POR CADA CUENTA SUMA LOS VALORES
		{
			if($i==$l["id_banco"])
			{
				$s +=$l["valorec"];	
				$cue=$l["cuenta"];
			}
		}
		if($s > 0)
		{
			$pdf->Cell(30,5,"CTA ".$cue,1,0,'L'); 
			$pdf->Cell(25,5,number_format($s,2),1,0,'R');
			$pdf->Ln();
			$tc +=$s;
		}
	}
	$pdf->Cell(30,5,"VALOR CONSIGDO",1,0,'L'); 
	$pdf->Cell(25,5,number_format($tc,2),1,0,'R');$pdf->Ln();
	$pdf->Cell(30,5,"PASA CAJA",1,0,'L'); 
	$pdf->Cell(25,5,"",1,0,'R');$pdf->Ln();
	$pdf->Cell(30,5,"TOTALES",1,0,'C'); 
	$pdf->Cell(25,5,number_format($tc,2),1,0,'R');$pdf->Ln();
$pdf->Output();
?>
