<?php

    ob_start(); /* La función ob_start() sirve para indicarle a PHP que se ha de iniciar el buffering de la salida, es decir, 
				  que debe empezar a guardar la salida en un bufer interno, en vez de enviarla al cliente. 
				  De modo que, aunque se escriba código HTML con echo o directamente fuera del código PHP, no se 
				  enviará al navegador hasta que se ordene explícitamente. O eventualmente, hasta que se acabe el 
				  procesamiento de todo el archivo PHP.*/
?>				  
	<page backtop="10%" backbottom="5%" backleft="5%" backright="5%">
		 <page_header>
             <div align="center"> <IMG SRC="public/img/header_control_pago.jpg" width="882" height="83"></div>
         </page_header>
         <page_footer>
            <table cellspacing="0" style="padding: 1px; width: 100%;  font-size: 8pt;>
            	<tr>
            		<td style="width: 33%; font-size: 8pt;">CODIGO: F16-PGF-S02</td>
            		<td style="width: 33%; font-size: 8pt;" align="center">VERSION: 01</td>
            		<td style="width: 33%; font-size: 8pt;" align="right">FECHA DE VIGENCIA: 011/09/2009</td>
            	</tr>
            </table>
            
          </page_footer>
	 	  <br />
	 	  <?php $num=$_GET["idnumi"];?>
	 	  									<div align="right"><?php echo "FECHA :".$tin[0]["fechain"];?></div>
	    <h4>COMPROBANTE DE INGRESO N°: <?php echo $num;?></h4>	
		<table cellspacing="0" style="padding: 1px; width: 100%; border: solid 2px #000000; font-size: 11pt; >
			<tr >
				<th style="width: 12%; border: solid 1px #000000;">RECIBIDO DE</th>
				<th style="width: 20%; border: solid 1px #000000;" align="center">CONCEPTO</th>
				<th style="width: 12%; border: solid 1px #000000;" align="center" >BANCO</th>
				<th style="width: 12%; border: solid 1px #000000;" align="center">CTA</th>
				<th style="width: 12%; border: solid 1px #000000;" align="center">FECHA</th>
				<th style="width: 12%; border: solid 1px #000000;" align="center">VALOR</th>
				<th style="width: 12%; border: solid 1px #000000;" align="center">CTA CONT.</th>
				<th style="width: 12%; border: solid 1px #000000;" align="center">FUNCIONARIO</th>
			</tr>
			<?php foreach($ting as $tg)
			{
				$idb=$tg["id_banco"];?>
		 		
				<?php foreach($tin as $t)
				{
					if($t["id_banco"]==$idb)
					{?>
						<tr >
						<td style="width: 12%; border: solid 1px #000000;"><?php echo $t["nombrecuenta"];?></td>
						<td style="width: 20%; border: solid 1px #000000;"><?php echo $t["concepto"];?></td>
						<td style="width: 12%; border: solid 1px #000000;"><?php echo $t["nombreban"];?></td>
						<td style="width: 12%; border: solid 1px #000000;" align="center"><?php echo $t["cuenta"];?></td>
						<td style="width: 12%; border: solid 1px #000000;" align="center"><?php echo $t["fechadeta"];?></td>
						<td style="width: 12%; border: solid 1px #000000;" align="right"><?php echo number_format($t["valordeta"],2);?></td>
						<td style="width: 12%; border: solid 1px #000000;" align="center"><?php echo $t["codigo"];?></td>
						<td style="width: 12%; border: solid 1px #000000;" align="center"><?php echo $t["nombre_func"];?></td>
						</tr>
					    <?php	
						$cue=$t["cuenta"];
						
						}
				
				
			    }
			    $numl=utf8_decode(Conectar::NumeroLetras($tles["valorin"]));	
				$numl=ucwords($numl);
			    ?>
				<tr>
					<td colspan="8" style="border: solid 1px #000000;" align="center"><?php echo 'TOTAL CTA No'.$cue.'     '.number_format($tg["valord"],2);?></td>
				</tr>
				<tr>
					<td colspan="8" ><?php echo ' .  ';?></td>
				</tr>
			<?php
			}?>
			<tr>
					<td colspan="8" style="border: solid 1px #000000;" align="left"><?php echo 'TOTAL CTAS :'.number_format($tles["valorin"],2);?></td>
			</tr>
			<tr>
					<td colspan="8" ><?php echo ' .  ';?></td>
			</tr>
			<tr>
					<td colspan="8"  align="left"><?php echo 'LA SUMA DE : '.$numl;?></td>
			</tr>
		</table>
		<br /><br /><br /><br />
		<?php echo $tles["nombre_func"];?><br />
		<?php echo "_______________________________________";?><br />
		<strong> Auxiliar de Tesoreria</strong>
			
	</page>			  
				  
				  
<?php    
    $content = ob_get_clean();

    // convert in PDF
    require_once('public/html2pdf//html2pdf.class.php');
    try
    {
        $html2pdf = new HTML2PDF('L', 'LETTER', 'es');
//      $html2pdf->setModeDebug();
        $html2pdf->setDefaultFont('Arial');
        $html2pdf->writeHTML($content);
        $html2pdf->Output('ingreso.pdf');
    }
    catch(HTML2PDF_exception $e) {
        echo $e;
        exit;
    }
