<?php
require_once("public/fpdf/fpdf.php");
class PDF extends FPDF
{
		
		//Cabecera de página
	
	function Header()
	{ 
	    $this->Image('public/img/header_control_pago.jpg',10,10,250,20);
		$this->Ln();
		$this->Ln(20);
			 
			 
		
	   		
	}

	//Pie de página
	function Footer()
	{
	    $this->SetXY(10,-15);
	    //Arial italic 8
	    $this->SetFont('Arial','I',8);
	    //Número de página
	    $this->Cell(35,5,'CODIGO: F16-PGF-S02');
		$ver='VERSION: 01';
		$w=$this->GetStringWidth($ver);
		$this->SetX((279-$w)/2);
	    $this->Cell($w,5,$ver); 
		$ver2='FECHA DE VIGENCIA: 011/09/2009';
		$w=$this->GetStringWidth($ver2)+10;
		$this->SetX((279-$w));
		$this->Cell($w,5,$ver2); 
	}
}

$dias = array("Domingo","Lunes","Martes","Miercoles","Jueves","Viernes","Sábado");
$meses = array("Enero","Febrero","Marzo","Abril","Mayo","Junio","Julio","Agosto","Septiembre","Octubre","Noviembre","Diciembre");
$fec= $dias[date('w')]." ".date('d')." de ".$meses[date('n')-1]. " del ".date('Y') ;

$pdf=new PDF('L', 'mm', 'Legal');
	$pdf->AliasNbPages();
	$pdf->AddPage();
	$pdf->Ln(10);
	$pdf->SetFont('Arial','B',10);
	$W=$pdf->GetStringWidth(utf8_decode('PLANILLA DIARIA PARA IDENTIFICACION Y CAUSACION DE INGRESOS'))+6;
	$pdf->Cell(70);
	$pdf->Cell($W,5,utf8_decode('PLANILLA DIARIA PARA IDENTIFICACION Y CAUSACION DE INGRESOS'),0,0,'L');$pdf->SetFont('');
	$pdf->SetFont('times','',20);
	$pdf->Ln();
	$pdf->SetFont('Arial','B',11);
	$pdf->Cell(180,5,'',0,0);
	$pdf->Cell(25,5,"Planilla No. ",0,0,'L');$pdf->SetFont('');
	$pdf->Cell(25,5,$_GET["idnump"],0,0,'L');$pdf->Ln();
	$pdf->SetFont('Arial','B',11);
	$pdf->Cell(180,5,'',0,0);
	$pdf->Cell(25,5,'FECHA :',0,0,'L');$pdf->SetFont('');
	$pdf->SetFont('Arial','',10);
	$pdf->Cell(30,5,$tpl[0]["fechain"],0,0,'L');
	$pdf->SetFont('Arial','B',8);
	$pdf->Ln(10);
	$pdf->Cell(2,5,'',0,0);
	//$pdf->SetFillColor(192,192,192);
	$pdf->Cell(25,5,'BANCO',1,0,'C');
	$pdf->Cell(20,5,'CTA',1,0,'C');
	$pdf->Cell(20,5,'FECHA',1,0,'C');
	$pdf->Cell(25,5,'VALOR',1,0,'C');
	$pdf->Cell(195,5,'CONCEPTO',1,0,'C');
	$pdf->Cell(20,5,'CTA CONT.',1,0,'C');
	$pdf->Cell(35,5,'FUNCIONARIO',1,0,'C');
	
	$pdf->Ln();
	foreach($tpla as $tg)
	{
		$idb=$tg["id_banco"];
		
		foreach($tpl as $t)
		{
			if($t["id_banco"]==$idb)
			{
				$pdf->Cell(2,5,'',0,0);	
				$pdf->SetFont('Arial','',7);
				$pdf->Cell(25,10,$t["nombreban"],1,0);
				$pdf->SetFont('Arial','',8);
				$pdf->Cell(20,10,$t["cuenta"],1,0,'R');
				$pdf->Cell(20,10,$t["fechadeta"],1,0);
				$pdf->Cell(25,10,number_format($t["valordeta"],2),1,0,'R');
				$y = $pdf->GetY();/*La función GetY nos guardará la posición de Y dentro del documento y lo almacenamos en una variable, al terminar de escribir la descripción regresamos nuestra posición a este valor para que las demas columnas aparezcan alineados con el resto.*/
				$pdf->SetFont('Arial','',7);
				$pdf->MultiCell(195,3,$t["concepto"],'T','J'); $pdf->SetXY(297,$y);
				$pdf->SetFont('');
				$pdf->SetFont('Arial','',8);
				$pdf->Cell(20,10,$t["codigo"],1,0);
				$pdf->Cell(35,10,$t["nombre_func"],1,0);
				$cue=$t["cuenta"];
				$fu=$t["nombre_func"];
				$pdf->Ln(10);
			}
		}
		$pdf->Cell(2,5,'',0,0);
		$pdf->Cell(340,5,'',1,0,'C');
		$pdf->Ln();$pdf->Ln();
	}
	
	$pdf->Ln();$pdf->Ln();
	$numl=utf8_decode(Conectar::NumeroLetras($tplas["valorin"]));	
	$numl=ucwords($numl);
	$W=$pdf->GetStringWidth($numl)+6;
	$pdf->Ln();
	$pdf->Ln(10);
	$pdf->SetFont('Arial','',10);
	$pdf->Cell(80,5,"Firma :",'B',0);$pdf->Ln();$pdf->Ln();
	$pdf->Cell(80,5,"Nombre :    ".$fu,'B',0);
	$pdf->Ln();
	$pdf->Cell(80,5,'Responsable Cartera',0,0,'C');
	
$pdf->Output();
?>
